# railway.toml
version = 1

[build]
  # Comando para compilar tu aplicación
  command = "cd backend && ./mvnw clean package"

[serve]
  # Comando para ejecutar tu aplicación
  command = "cd backend && ./mvnw spring-boot:run"

# Opcional: puedes establecer el entorno en producción o desarrollo
[env]
  # Aquí puedes agregar tus variables de entorno

# Opcional: puedes especificar la versión de Java que deseas usar
[plugins]
  [plugins.java]
    version = "17"  
